POST http://localhost:8080/api/v1/private/user/?lang=en_US&store=mystore
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBzaG9waXplci5jb20iLCJhdWQiOiJhcGkiLCJleHAiOjE2NzE0MTQwMDgsImlhdCI6MTY3MDgwOTIwOH0.EKtQkZ2jwIQtjuWmDrbNJTepVwK9mCCRBTvkDzBng7jN7SOz0zK36nT91LDIE85ybe12NJBsAu-F7M0tOxdmoQ
Content-Type: application/json

{
  "emailAddress": "test@local.dev",
  "merchant": "mystore",
  "firstName": "Peng",
  "lastName": "Wang",
  "userName": "test@local.dev",
  "groups": [
    {
      "name": "ADMIN",
      "type": "ADMIN",
      "id": 351
    },
    {
      "name": "ADMIN_RETAILER",
      "type": "ADMIN",
      "id": 352
    }
  ],
  "defaultLanguage": "en",
  "active": true,
  "password": "X*bcYp4x",
  "repeatPassword": "X*bcYp4x"
}

###
GET http://localhost:8080/api/v1/languages

###
POST http://localhost:8080/api/v1/private/login
Content-Type: application/json

{
  "username": "admin@shopizer.com",
  "password": "password"
}

###
GET http://localhost:8080/api/v1/private/store/DEFAULT?lang=en&store=DEFAULT
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBzaG9waXplci5jb20iLCJhdWQiOiJhcGkiLCJleHAiOjE2NzE1OTA1MzcsImlhdCI6MTY3MDk4NTczN30.iKPHIVaLTFg8pKo_LYhUUn-soSzU9phaBHwSl7g67-izNPDj2lvhpRUhswJnfmBLWA-zeG4reGEHliguqQQ3tg
